from apify_client import ApifyClient
from dotenv import load_dotenv
import os



# Load environment variables from .env file
load_dotenv()
apify_api_token = os.getenv('apify_api_token')

# Initialize the ApifyClient with your Apify API token
# Replace '<YOUR_API_TOKEN>' with your token.
client = ApifyClient(f'{apify_api_token}')

# Create a list of restaurant URLs to scrape
restaurant_url = [
    "https://www.opentable.com/r/haru-ichiban-duluth",
    "https://www.opentable.com/r/red-room-bistro-atlanta",
    "https://www.opentable.com/r/el-gordo-atlanta",     
    "https://www.opentable.com/r/the-chastain-atlanta",
    "https://www.opentable.com/r/longleaf-restaurant-atlanta",
    "https://www.opentable.com/r/fogo-de-chao-brazilian-steakhouse-atlanta",
    "https://www.opentable.com/r/longleaf-restaurant-atlanta",
    "https://www.opentable.com/r/rumis-kitchen-colony-square-midtown-atlanta",
    "https://www.opentable.com/r/osteria-mattone-yurt-experience-roswell",
    "https://www.opentable.com/r/aria-atlanta",
    "https://www.opentable.com/r/casa-coya-atlanta",
    "https://www.opentable.com/r/el-gordo-atlanta",
    "https://www.opentable.com/r/osteria-mattone-yurt-experience-roswell",
    "https://www.opentable.com/r/stk-atlanta",
    "https://www.opentable.com/r/bistro-niko",
    "https://www.opentable.com/r/little-alley-steak-buckhead-suite-100",
    "https://www.opentable.com/r/atrium-atlanta",
    "https://www.opentable.com/r/yeppa-and-co-buckhead",
    "https://www.opentable.com/r/the-big-ketch-atlanta",
    "https://www.opentable.com/r/the-palm-atlanta",
    "https://www.opentable.com/r/new-york-prime-steakhouse-atlanta",
    "https://www.opentable.com/r/saints-and-council-atlanta",
    "https://www.opentable.com/r/eclipse-di-luna-buckhead-atlanta",
    "https://www.opentable.com/r/mission-and-market-atlanta",
    "https://www.opentable.com/r/murphys-atlanta",
    "https://www.opentable.com/r/mission-and-market-atlanta",
    "https://www.opentable.com/r/carmel-atlanta",
    "https://www.opentable.com/r/le-colonial-atlanta",
    "https://www.opentable.com/ruths-chris-steak-house-buckhead",
    "https://www.opentable.com/f-and-b-atlanta",
    "https://www.opentable.com/gypsy-kitchen",
    "https://www.opentable.com/r/beetlecat-atlanta",
    "https://www.opentable.com/atlanta-fish-market",
    "https://www.opentable.com/r/storico-fresco-alimentari-e-ristorante-atlanta",
    "https://www.opentable.com/r/serena-pastificio-atlanta",
    "https://www.opentable.com/r/amalfi-cucina-and-mercato-buckhead-atlanta",
    "https://www.opentable.com/flemings-steakhouse-atlanta",
    "https://www.opentable.com/r/nakato-japanese-restaurant-hibachi-teppanyaki-grill-atlanta",
    "https://www.opentable.com/r/white-oak",
    "https://www.opentable.com/r/grana-piedmont-atlanta",
    "https://www.opentable.com/r/eataliano-kitchen-brookhaven-atlanta",
    "https://www.opentable.com/r/double-zero-atlanta",
    "https://www.opentable.com/r/little-sparrow-atlanta",
    "https://www.opentable.com/gypsy-kitchen",
    "https://www.opentable.com/pricci",
    "https://www.opentable.com/r/nan-thai-fine-dining-atlanta",
    "https://www.opentable.com/r/joey-ds-oak-room-atlanta",
    "https://www.opentable.com/the-southern-gentleman",
    "https://www.opentable.com/pricci",
    "https://www.opentable.com/r/serena-pastificio-atlanta",
    "https://www.opentable.com/r/storico-fresco-alimentari-e-ristorante-atlanta",
    "https://www.opentable.com/r/beetlecat-atlanta",
    "https://www.opentable.com/r/nan-thai-buckhead-atlanta",
    "https://www.opentable.com/r/nobu-atlanta",
    "https://www.opentable.com/r/the-americano-atlanta",
    "https://www.opentable.com/atlanta-fish-market",
    "https://www.opentable.com/r/anis-cafe-and-bistro",
    "https://www.opentable.com/ruths-chris-steak-house-buckhead",
    "https://www.opentable.com/r/the-big-ketch-atlanta",
    "https://www.opentable.com/r/prime-on-peachtree-atlanta",
    "https://www.opentable.com/le-bilboquet-atlanta",
    "https://www.opentable.com/r/the-iberian-pig-decatur",
    "https://www.opentable.com/alma-cocina",
    "https://www.opentable.com/r/marcel-atlanta",
    "https://www.opentable.com/poor-calvins",
    "https://www.opentable.com/r/nakato-japanese-restaurant-hibachi-teppanyaki-grill-atlanta",
    "https://www.opentable.com/r/white-oak",
    "https://www.opentable.com/r/ninos-atlanta",
    "https://www.opentable.com/r/divan-restaurant-and-bar-atlanta",
    "https://www.opentable.com/r/amalfi-cucina-and-mercato-buckhead-atlanta",
    "https://www.opentable.com/r/two-urban-licks-atlanta",
    "https://www.opentable.com/valenza-restaurant",
    "https://www.opentable.com/r/igloos-at-9-mile-station-atlanta",
    "https://www.opentable.com/r/enso-izakaya-avondale-estates",
    "https://www.opentable.com/r/arnettes-chop-shop-brookhaven",
    "https://www.opentable.com/r/amalfi-cucina-and-mercato-downtown-atlanta",
    "https://www.opentable.com/r/the-betty-atlanta",
    "https://www.opentable.com/r/fogo-de-chao-brazilian-steakhouse-atlanta",
    "https://www.opentable.com/la-grotta",
    "https://www.opentable.com/r/cooks-and-soldiers-atlanta",
    "https://www.opentable.com/r/ecco-buckhead",
    "https://www.opentable.com/r/kitchen-and-kocktails-atlanta-dunwoody",
    "https://www.opentable.com/r/grana-piedmont-atlanta",
    "https://www.opentable.com/r/ela-atlanta",
    "https://www.opentable.com/r/zakia-atlanta",
    "https://www.opentable.com/r/max-lagers-wood-fired-grill-and-brewery",
    "https://www.opentable.com/r/c-and-s-seafood-and-oyster-bar-brookhaven-atlanta",
    "https://www.opentable.com/r/south-city-kitchen-buckhead-atlanta",
    "https://www.opentable.com/r/superica-buckhead-atlanta-2",
    "https://www.opentable.com/r/buena-vida-tapas-bar-atlanta",
    "https://www.opentable.com/r/white-bull-decatur",
    "https://www.opentable.com/r/holeman-and-finch-pubic-house-atlanta",
    "https://www.opentable.com/r/eataliano-kitchen-brookhaven-atlanta",
    "https://www.opentable.com/r/sebastian-pintxos-bar-atlanta",
    "https://www.opentable.com/r/rays-in-the-city-atlanta",
    "https://www.opentable.com/r/petite-violette-atlanta",
    "https://www.opentable.com/r/flemings-steakhouse-atlanta",
    "https://www.opentable.com/r/local-three-atlanta",
    "https://www.opentable.com/r/terra-terroir",
    "https://www.opentable.com/r/botica-atlanta",
    "https://www.opentable.com/r/bar-bacoa-atlanta",
    "https://www.opentable.com/r/rays-on-the-river-sandy-springs",
    "https://www.opentable.com/r/roshambo-atlanta",
    "https://www.opentable.com/r/the-woodall-atlanta",
    "https://www.opentable.com/r/srithai-thai-kitchen-and-sushi-bar-emory-point-atlanta",
    "https://www.opentable.com/r/tulum-kitchen-and-bar-atlanta",
    "https://www.opentable.com/r/culinary-dropout-perimeter-dunwoody",
    "https://www.opentable.com/r/the-select-atlanta",
    "https://www.opentable.com/r/casi-cielo-mexican-cuisine-atlanta",
    "https://www.opentable.com/r/delbar-old-milton",
    "https://www.opentable.com/r/the-sun-dial-restaurant-bar-and-view-atlanta",
    "https://www.opentable.com/r/101-steak-atlanta",
    "https://www.opentable.com/r/tomo-japanese-restaurant-buckhead-atlanta",
    "https://www.opentable.com/r/hartley-atlanta",
    "https://www.opentable.com/r/margaritaville-atlanta",
    "https://www.opentable.com/r/rays-on-the-river-sandy-springs",
    "https://www.opentable.com/r/park-tavern-atlanta",
    "https://www.opentable.com/r/the-capital-grille-atlanta-buckhead-village-atlanta",
    "https://www.opentable.com/r/hobnob-neighborhood-tavern-brookhaven",
    "https://www.opentable.com/mf-sushi-atlanta",
    "https://www.opentable.com/seven-lamps",
    "https://www.opentable.com/r/tin-lizzys-midtown-atlanta-2",
    "https://www.opentable.com/r/knife-modern-mediterranean-atlanta",
    "https://www.opentable.com/r/tiny-lous-hotel-clermont-atlanta",
    "https://www.opentable.com/r/grana-ashford-atlanta",
    "https://www.opentable.com/eclipse-di-luna-dunwoody",
    "https://www.opentable.com/r/confab-kitchen-and-bar-atlanta",
    "https://www.opentable.com/r/hobnob-atlantic-station-atlanta",
    "https://www.opentable.com/r/tin-lizzys-atlanta",
    "https://www.opentable.com/r/melting-pot-atlanta",
    "https://www.opentable.com/r/bold-monk-brewing-co-atlanta",
    "https://www.opentable.com/r/indaco-atlanta",
    "https://www.opentable.com/r/bangkok-station",
    "https://www.opentable.com/r/atrium-atlanta",
    "https://www.opentable.com/r/toscano-ristorante-italiano-at-atlantic-station-atlanta",
    "https://www.opentable.com/r/kinjo-room-atlanta",
    "https://www.opentable.com/r/superica-krog-atlanta",
    "https://www.opentable.com/r/chico-cantina-atlanta",
    "https://www.opentable.com/r/brasserie-lundi-atlanta",
    "https://www.opentable.com/r/chicheria-mexican-kitchen-atlanta",
    "https://www.opentable.com/r/madre-selva-atlanta",
    "https://www.opentable.com/r/pendolino-atlanta",
    "https://www.opentable.com/r/canoe-atlanta",
    "https://www.opentable.com/r/rose-and-crown-marietta",
    "https://www.opentable.com/benihana-alpharetta",
    "https://www.opentable.com/r/maggianos-buckhead",
    "https://www.opentable.com/r/nakato-japanese-restaurant-sushi-bar-and-regular-dining-atlanta",
    "https://www.opentable.com/r/muss-and-turners-smyrna",
    "https://www.opentable.com/r/by-george-atlanta",
    "https://www.opentable.com/r/brooklyn-cafe-sandy-springs",
    "https://www.opentable.com/r/o-ku-atlanta",
    "https://www.opentable.com/r/sugar-factory-american-brasserie-atlanta",
    "https://www.opentable.com/r/boqueria-colony-square-atlanta",
    "https://www.opentable.com/r/rreal-tacos-decatur",
    "https://www.opentable.com/r/sea-salt-atlanta",
    "https://www.opentable.com/mali-restaurant",
    "https://www.opentable.com/r/tabla-midtown-atlanta",
    "https://www.opentable.com/r/hobnob-neighborhood-tavern-vinings-atlanta",
    "https://www.opentable.com/r/hobnob-neighborhood-tavern-dunwoody-atlanta",
    "https://www.opentable.com/r/tuk-tuk-thai-food-loft-atlanta",
    "https://www.opentable.com/r/zocalo-atlanta",
    "https://www.opentable.com/r/aria-atlanta",
    "https://www.opentable.com/r/cuts-steakhouse-atlanta",
    "https://www.opentable.com/r/o-ku-atlanta",
    "https://www.opentable.com/r/basils-restaurant-and-tapas-bar",
    "https://www.opentable.com/r/terenga-city-restaurant-and-lounge-brookhaven-atlanta",
    "https://www.opentable.com/r/eclipse-di-luna-krog-atlanta",
    "https://www.opentable.com/r/midtown-social-restaurant-and-bar-atlanta",
    "https://www.opentable.com/r/fia-restaurant-atlanta",
    "https://www.opentable.com/true-food-kitchen-atlanta",
    "https://www.opentable.com/r/tre-vele-sandy-springs",
    "https://www.opentable.com/r/pf-changs-atlanta-perimeter-atlanta-2",
    "https://www.opentable.com/r/snap-thai-fish-house-atlanta",
    "https://www.opentable.com/ruths-chris-steak-house-centennial-park",
    "https://www.opentable.com/r/belen-bistro-decatur",
    "https://www.opentable.com/r/silom-thai-and-sushi-bar-atlanta",
    "https://www.opentable.com/r/north-italia-buckhead-atlanta",
    "https://www.opentable.com/r/silla-del-toro-toco-hills-atlanta",
    "https://www.opentable.com/r/sugo-duluth",
    "https://www.opentable.com/r/portico-atlanta",
    "https://www.opentable.com/r/atalian-atlanta",
    "https://www.opentable.com/r/the-local-tavern-atlanta",
    "https://www.opentable.com/r/agora-midtown-atlanta",
    "https://www.opentable.com/ruths-chris-steak-house-alpharetta",
    "https://www.opentable.com/r/crescent-city-kitchen-atlanta",
    "https://www.opentable.com/pacific-rim-bistro",
    "https://www.opentable.com/south-city-kitchen-vinings",
    "https://www.opentable.com/r/seasons-52-perimeter-dunwoody-2",
    "https://www.opentable.com/r/truva-virginia-highlands-atlanta",
    "https://www.opentable.com/r/campagnolo-atlanta",
    "https://www.opentable.com/r/ct-reforma-buckhead-atlanta",
    "https://www.opentable.com/r/seed-kitchen-and-bar-marietta",
    "https://www.opentable.com/r/emilios-tacos-and-tequila-atlanta",
    "https://www.opentable.com/r/rreal-tacos-west-midtown-atlanta",
    "https://www.opentable.com/r/c-ellets-steakhouse-atlanta",
    "https://www.opentable.com/r/serenity-bar-lounge-atlanta",
    "https://www.opentable.com/r/gyu-kaku-japanese-bbq-atlanta-ga-atlantic-station",
    "https://www.opentable.com/r/rosa-atlanta",
    "https://www.opentable.com/r/nowaks-steakhouse-sandy-springs",
    "https://www.opentable.com/r/ag-modern-steakhouse-atlanta",
    "https://www.opentable.com/r/eataliano-kitchen-the-battery-atlanta",
    "https://www.opentable.com/r/pampas-steakhouse-alpharetta",
    "https://www.opentable.com/r/pf-changs-atlanta-cumberland-atlanta",
    "https://www.opentable.com/r/wicked-wolf-atlanta",
    "https://www.opentable.com/r/h-and-w-steakhouse-norcross",
    "https://www.opentable.com/r/hopstix-chamblee",
    "https://www.opentable.com/r/nala-kitchen-and-cocktails-sandy-springs",
    "https://www.opentable.com/r/309-social-atlanta",
    "https://www.opentable.com/r/brassica-atlanta",
    "https://www.opentable.com/r/rreal-tacos-chamblee-atlanta",
    "https://www.opentable.com/r/baraonda-sandy-springs",
    "https://www.opentable.com/r/varasanos-pizzeria",
    "https://www.opentable.com/r/mckendricks-steakhouse-perimeter-center-atlanta",
    "https://www.opentable.com/r/tesserae-atlanta",
    "https://www.opentable.com/r/reverence-atlanta",
    "https://www.opentable.com/r/mrs-ps-bar-and-kitchen-atlanta",
    "https://www.opentable.com/r/c-and-s-seafood-and-oyster-bar-sandy-springs",
    "https://www.opentable.com/r/ct-cantina-and-taqueria-dunwoody",
    "https://www.opentable.com/r/escovitchez-atlanta",
    "https://www.opentable.com/r/spice-house-midtown-atlanta",
    "https://www.opentable.com/r/redeye-southern-kitchen-hapeville",
    "https://www.opentable.com/r/the-capital-grille-atlanta-dunwoody-perimeter-mall-atlanta",
    "https://www.opentable.com/r/fado-irish-pub-atlanta-1",
    "https://www.opentable.com/r/trade-root-restaurant-and-lounge-atlanta",
    "https://www.opentable.com/r/crispina-ristorante-and-pizzeria-atlanta",
    "https://www.opentable.com/r/paschals-restaurant-atlanta",
    "https://www.opentable.com/r/dave-and-busters-alpharetta",
    "https://www.opentable.com/glenns-kitchen-atlanta",
    "https://www.opentable.com/r/prime-cigar-bar-atlanta",
    "https://www.opentable.com/taka-sushi",
    "https://www.opentable.com/r/superica-dunwoody",
    "https://www.opentable.com/r/pf-changs-alpharetta",
    "https://www.opentable.com/zibas-bistro",
    "https://www.opentable.com/hard-rock-cafe-atlanta",
    "https://www.opentable.com/thrive",
    "https://www.opentable.com/r/beechwood-tavern-atlanta",
    "https://www.opentable.com/r/new-realm-brew-pub-atlanta",
    "https://www.opentable.com/r/little-alley-steak-roswell",
    "https://www.opentable.com/r/fado-irish-pub-midtown-atlanta",
    "https://www.opentable.com/r/the-hampton-social-atlanta",
    "https://www.opentable.com/r/cibo-e-beve-sandy-springs",
    "https://www.opentable.com/r/dave-and-busters-marietta-atlanta-marietta",
    "https://www.opentable.com/r/pom-court-atlanta",
    "https://www.opentable.com/sufis-atlanta-buckhead",
    "https://www.opentable.com/r/who-wanna-pho-atlanta",
    "https://www.opentable.com/r/pour-taproom-midtown-atlanta",
    "https://www.opentable.com/r/chelo-roswell",
    "https://www.opentable.com/r/dos-caminos-atlanta",
    "https://www.opentable.com/r/lazy-dog-restaurant-and-bar-dunwoody",
    "https://www.opentable.com/r/park-82-atlanta",
    "https://www.opentable.com/r/grana-roswell",
    "https://www.opentable.com/r/gianni-and-macs-ristorante-piazza-nostra-atlanta",
    "https://www.opentable.com/r/the-preserve-atlanta",
    "https://www.opentable.com/r/rowdy-tiger-atlanta",
    "https://www.opentable.com/r/table-and-main-roswell",
    "https://www.opentable.com/r/brewdog-atlanta",
    "https://www.opentable.com/r/renas-italian-fishery-and-grill-alpharetta",
    "https://www.opentable.com/r/melting-pot-duluth-2",
    "https://www.opentable.com/r/north-italia-perimeter-dunwoody",
    "https://www.opentable.com/r/rreal-tacos-sandy-springs",
    "https://www.opentable.com/r/luga-marietta",
    "https://www.opentable.com/r/la-petite-maison-sandy-springs",
    "https://www.opentable.com/r/restaurant-10-atlanta",
    "https://www.opentable.com/r/osteria-mattone-roswell",
    "https://www.opentable.com/r/soho-atlanta",
    "https://www.opentable.com/r/bonefish-grill-akers-mill-atlanta",
    "https://www.opentable.com/r/dos-bocas-atlanta",
    "https://www.opentable.com/r/commons-restaurant-and-bar-atlanta",
    "https://www.opentable.com/zafron-restaurant",
    "https://www.opentable.com/r/porfirios-atlanta",
    "https://www.opentable.com/r/maggianos-perimeter",
    "https://www.opentable.com/r/metrofresh-atlanta",
    "https://www.opentable.com/r/yao-dunwoody",
    "https://www.opentable.com/genki-noodles-and-sushi-prado",
    "https://www.opentable.com/r/wylie-and-rum-island-bar-and-grill-atlanta",
    "https://www.opentable.com/hugos-oyster-bar",
    "https://www.opentable.com/r/macs-chophouse-marietta",
    "https://www.opentable.com/r/zekes-kitchen-and-bar-west-midtown-atlanta",
    "https://www.opentable.com/r/bask-steakhouse-roswell",
    "https://www.opentable.com/r/macs-raw-bar-marietta",
    "https://www.opentable.com/r/red-lobster-tucker",
    "https://www.opentable.com/r/the-daiquiri-factory-atlanta",
    "https://www.opentable.com/big-kahuna",
    "https://www.opentable.com/r/emmy-squared-pizza-midtown-west-atl-atlanta",
    "https://www.opentable.com/r/crus-food-and-wine-bar-the-battery-atlanta",
    "https://www.opentable.com/r/eddie-vs-alpharetta",
    "https://www.opentable.com/r/catch-twelve-atlanta",
    "https://www.opentable.com/r/rays-at-killer-creek-alpharetta",
    "https://www.opentable.com/r/emmy-squared-pizza-glenwood-park-atlanta",
    "https://www.opentable.com/r/parkwoods-atlanta",
    "https://www.opentable.com/r/red-pepper-taqueria-dunwoody",
    "https://www.opentable.com/r/prickly-pear-tapas-tacos-and-tequilla-atlanta",
    "https://www.opentable.com/r/trattoria-one-41-johns-creek",
    "https://www.opentable.com/1920-tavern-at-opulent",
    "https://www.opentable.com/r/coopers-hawk-winery-and-restaurant-alpharetta-ga-alpharetta",
    "https://www.opentable.com/r/maggianos-cumberland",
    "https://www.opentable.com/savor-bar-and-kitchen",
    "https://www.opentable.com/r/mccrays-tavern-east-cobb-marietta",
    "https://www.opentable.com/r/punch-bowl-social-atlanta-2",
    "https://www.opentable.com/r/silla-del-toro-roswell",
    "https://www.opentable.com/mccrays-tavern-west-village",
    "https://www.opentable.com/r/national-anthem-atlanta",
    "https://www.opentable.com/r/olive-bistro-atlanta",
    "https://www.opentable.com/r/ssamjang-korean-bbq-atlanta",
    "https://www.opentable.com/r/good-game-restaurant-and-bar-at-the-battery-atlanta",
    "https://www.opentable.com/r/camps-kitchen-and-bar-marietta",
    "https://www.opentable.com/r/aprons-atlanta",
    "https://www.opentable.com/r/waterside-restaurant-1-stone-mountain",
    "https://www.opentable.com/r/firebirds-wood-fired-grill-peachtree-corners",
    "https://www.opentable.com/r/kurts-euro-bistro-duluth",
    "https://www.opentable.com/r/viceroy-royal-indian-dining",
    "https://www.opentable.com/r/tosca-blu-renaissance-atlanta-waverly-hotel-and-convention-center-atlanta",
    "https://www.opentable.com/chicagos-roswell",
    "https://www.opentable.com/r/sei-ryu-peachtree-corners",
    "https://www.opentable.com/r/mexico-lindo-smyrna",
    "https://www.opentable.com/r/b-and-w-burgers-buns-and-brews-norcross",
    "https://www.opentable.com/r/dahlias-restaurant-and-porch-norcross",
    "https://www.opentable.com/r/red-lobster-decatur-2",
    "https://www.opentable.com/r/three-roses-tavern-marietta",
    "https://www.opentable.com/r/blue-moon-brewery-and-grill-atlanta",
    "https://www.opentable.com/r/on-north-eatery-and-bar-marietta",
    "https://www.opentable.com/r/nancys-chicago-pizzeria-roswell",
    "https://www.opentable.com/r/sabores-del-plata-norcross",
    "https://www.opentable.com/r/fresca-trattoria-atlanta",
    "https://www.opentable.com/r/haru-ichiban-duluth",
    "https://www.opentable.com/r/fumi-hibachi-and-sushi-bar-duluth",
    "https://www.opentable.com/r/azotea-cantina-roswell",
    "https://www.opentable.com/r/local-on-north-duluth-marietta",
    "https://www.opentable.com/r/red-lobster-snellville",
    "https://www.opentable.com/r/osteria-mattone-yurt-experience-roswell",
    "https://www.opentable.com/r/spice-house-lithonia",
    "https://www.opentable.com/r/vatica-indian-cuisine-marietta",
    "https://www.opentable.com/r/red-lobster-smyrna",
    "https://www.opentable.com/r/red-lobster-atlanta",
    "https://www.opentable.com/bentleys-steakhouse",
    "https://www.opentable.com/r/bahama-breeze-atlanta-gwinnett-duluth",
    "https://www.opentable.com/r/king-claw-morrow",
    "https://www.opentable.com/r/table-and-main-yurt-experience-roswell",
    "https://www.opentable.com/r/red-lobster-duluth",
    "https://www.opentable.com/r/golfvx-duluth",
    "https://www.opentable.com/r/voodoo-brewing-co-roswell-ga-roswell",
    "https://www.opentable.com/r/lazy-dog-restaurant-and-bar-alpharetta",
    "https://www.opentable.com/r/melting-pot-roswell",
    "https://www.opentable.com/r/red-lobster-austell",
    "https://www.opentable.com/r/kitchen141-alpharetta",
    "https://www.opentable.com/r/unknown-atlanta"
    
]

restaurant_url = list(set(restaurant_url))

# Create an empty list to hold the dictionary 
url_list = []
for url in restaurant_url:
    restaurant_dict = {"url": url}
    url_list.append(restaurant_dict)
# Prepare the Actor input using a for loop to go through the list

run_input = {
    "startUrls": url_list,
    "proxy": {
        "useApifyProxy": True,
        "apifyProxyGroups": ["RESIDENTIAL"],
    },
}


# Run the Actor and wait for it to finish
run = client.actor("memo23/opentable-reviews-cheerio").call(run_input=run_input)

# Fetch and print Actor results from the run's dataset (if there are any)
print("💾 Check your data here: https://console.apify.com/storage/datasets/" + run["defaultDatasetId"])
for item in client.dataset(run["defaultDatasetId"]).iterate_items():
    print(item)

